---

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - make
    - gcc
  become: yes

- name: clear state
  file:
    path: /tmp/re2-{{ libre2_version }}
    state: absent
  become: yes

- name: fetch google/re2
  unarchive:
    src: ttps://github.com/google/re2/archive/{{ libre2_version }}.tar.gz
    dest: /tmp
    remote_src: True

- name: configure
  command: ./configure
  args:
    chdir: /tmp/re2-{{ libre2_version }}

- name: make
  command: make
  args:
    chdir: /tmp/re2-{{ libre2_version }}

- name: install
  command: make install
  args:
    chdir: /tmp/re2-{{ libre2_version }} 
  become: yes
